DROP DATABASE IF EXISTS manageruser;
DROP USER IF EXISTS `root`@`%`;
CREATE DATABASE IF NOT EXISTS manageruser CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS `admin`@`%` IDENTIFIED WITH mysql_native_password BY 'Test123@';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, REFERENCES, INDEX, ALTER, EXECUTE, CREATE VIEW, SHOW VIEW,
CREATE ROUTINE, ALTER ROUTINE, EVENT, TRIGGER ON `admin`.* TO `admin`@`%`;